spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: redis_docker
      port: 6379
